export const icd_data = 
[{"M25.511":"Pain in right shoulder"},
{"M25.561":"Pain in right knee"},
{"M25.562":"Pain in left knee"},
{"M54.50":"Low back pain, unspecified"},
{"M25.512":"Pain in left shoulder"},
{"M54.2":"Cervicalgia"},
{"M62.81":"Muscle weakness (generalized)"},
{"M25.551":"Pain in right hip"},
{"M25.571":"Pain in right ankle and joints of right foot"},
{"M25.572":"Pain in left ankle and joints of left foot"},
{"M25.552":"Pain in left hip"},
{"M54.51":"Vertebrogenic low back pain"},
{"R26.2":"Difficulty in walking, not elsewhere classified"},
{"R53.1":"Weakness"},
{"M54.6":"Pain in thoracic spine"},
{"M79.672":"Pain in left foot"},
{"M79.671":"Pain in right foot"},
{"R42":"Dizziness and giddiness"},
{"R26.81":"Unsteadiness on feet"},
{"A00.0":"Cholera due to Vibrio cholerae 01, biovar cholerae"},
{"M79.605":"Pain in left leg"},
{"M25.521":"Pain in right elbow"},
{"M54.16":"Radiculopathy, lumbar region"},
{"M25.641":"Stiffness of right hand, not elsewhere classified"},
{"R41.841":"Cognitive communication deficit"},
{"M25.531":"Pain in right wrist"},
{"M79.604":"Pain in right leg"},
{"M54.12":"Radiculopathy, cervical region"},
{"M25.532":"Pain in left wrist"},
{"I89.0":"Lymphedema, not elsewhere classified"},
{"M25.522":"Pain in left elbow"},
{"R06.00":"Dyspnea, unspecified"},
{"M54.41":"Lumbago with sciatica, right side"},
{"M51.36":"Other intervertebral disc degeneration, lumbar region"},
{"M25.631":"Stiffness of right wrist, not elsewhere classified"},
{"M25.642":"Stiffness of left hand, not elsewhere classified"},
{"R49.0":"Dysphonia"},
{"M79.602":"Pain in left arm"},
{"I63.9":"Cerebral infarction, unspecified"},
{"M79.601":"Pain in right arm"},
{"M25.672":"Stiffness of left ankle, not elsewhere classified"},
{"N39.3":"Stress incontinence (female) (male)"},
{"M19.011":"Primary osteoarthritis, right shoulder"},
{"M54.31":"Sciatica, right side"},
{"I97.2":"Postmastectomy lymphedema syndrome"},
{"G35":"Multiple sclerosis"},
{"M75.102":"Unspecified rotator cuff tear or rupture of left shoulder, not specified as traumatic"},
{"G25.0":"Essential tremor"},
{"M79.641":"Pain in right hand"},
{"M46.1":"Sacroiliitis, not elsewhere classified"},
{"M72.2":"Plantar fascial fibromatosis"},
{"M75.121":"Complete rotator cuff tear or rupture of right shoulder, not specified as traumatic"},
{"M76.62":"Achilles tendinitis, left leg"},
{"R51.9":"Headache, unspecified"},
{"M77.11":"Lateral epicondylitis, right elbow"},
{"M25.541":"Pain in joints of right hand"},
{"M25.611":"Stiffness of right shoulder, not elsewhere classified"},
{"R10.2":"Pelvic and perineal pain"},
{"M17.0":"Bilateral primary osteoarthritis of knee"},
{"M25.632":"Stiffness of left wrist, not elsewhere classified"},
{"M75.41":"Impingement syndrome of right shoulder"},
{"N39.46":"Mixed incontinence"},
{"G80.1":"Spastic diplegic cerebral palsy"},
{"F80.1":"Expressive language disorder"},
{"M54.42":"Lumbago with sciatica, left side"},
{"M17.12":"Unilateral primary osteoarthritis, left knee"},
{"M23.51":"Chronic instability of knee, right knee"},
{"M76.61":"Achilles tendinitis, right leg"},
{"M53.2X5":"Spinal instabilities, thoracolumbar region"},
{"R27.0":"Ataxia, unspecified"},
{"R47.1":"Dysarthria and anarthria"},
{"R41.89":"Other symptoms and signs involving cognitive functions and awareness"},
{"M48.062":"Spinal stenosis, lumbar region with neurogenic claudication"},
{"R10.30":"Lower abdominal pain, unspecified"},
{"G20.C":"Parkinsonism, unspecified"},
{"M79.642":"Pain in left hand"},
{"N39.41":"Urge incontinence"},
{"M17.11":"Unilateral primary osteoarthritis, righ knee"},
{"M54.32":"Sciatica, left side"},
{"M25.671":"Stiffness of right ankle, not elsewhere classified"},
{"M25.542":"Pain in joints of left hand"},
{"M76.32":"Iliotibial band syndrome, left leg"},
{"G62.9":"Polyneuropathy, unspecified"},
{"M25.612":"Stiffness of Left Shoulder"},
{"G20.B2":"Parkinson's disease with dyskinesia, with fluctuations"},
{"M19.012":"Osteoarthritis of Left shoulder"},
{"R49.8":"Other voice and resonance dx"},
{"R47.01":"Aphasia"},
{"R47.1":"Dysarthria"},
{"R48.2":"Apraxia"},
{"F80.1":"Expressive language disorder"},
{"R13.9":"Dysphagia"},
{"R41.844":"Frontal lobe and executive function deficit"}];

