export const icd_data = 
[{"code":"M25.511","name":"Pain in right shoulder"},
    {"code":"M25.561","name":"Pain in right knee"},
    {"code":"M25.562","name":"Pain in left knee"},
    {"code":"M54.50","name":"Low back pain, unspecified"},
    {"code":"M25.512","name":"Pain in left shoulder"},
    {"code":"M54.2","name":"Cervicalgia"},
    {"code":"M62.81","name":"Muscle weakness (generalized)"},
    {"code":"M25.551","name":"Pain in right hip"},
    {"code":"M25.571","name":"Pain in right ankle and joints of right foot"},
    {"code":"M25.572","name":"Pain in left ankle and joints of left foot"},
    {"code":"M25.552","name":"Pain in left hip"},
    {"code":"M54.51","name":"Vertebrogenic low back pain"},
    {"code":"R26.2","name":"Difficulty in walking, not elsewhere classified"},
    {"code":"R53.1","name":"Weakness"},
    {"code":"M54.6","name":"Pain in thoracic spine"},
    {"code":"M79.672","name":"Pain in left foot"},
    {"code":"M79.671","name":"Pain in right foot"},
    {"code":"R42","name":"Dizziness and giddiness"},
    {"code":"R26.81","name":"Unsteadiness on feet"},
    {"code":"A00.0","name":"Cholera due to Vibrio cholerae 01, biovar cholerae"},
    {"code":"M79.605","name":"Pain in left leg"},
    {"code":"M25.521","name":"Pain in right elbow"},
    {"code":"M54.16","name":"Radiculopathy, lumbar region"},
    {"code":"M25.641","name":"Stiffness of right hand, not elsewhere classified"},
    {"code":"R41.841","name":"Cognitive communication deficit"},
    {"code":"M25.531","name":"Pain in right wrist"},
    {"code":"M79.604","name":"Pain in right leg"},
    {"code":"M54.12","name":"Radiculopathy, cervical region"},
    {"code":"M25.532","name":"Pain in left wrist"},
    {"code":"I89.0","name":"Lymphedema, not elsewhere classified"},
    {"code":"M25.522","name":"Pain in left elbow"},
    {"code":"R06.00","name":"Dyspnea, unspecified"},
    {"code":"M54.41","name":"Lumbago with sciatica, right side"},
    {"code":"M51.36","name":"Other intervertebral disc degeneration, lumbar region"},
    {"code":"M25.631","name":"Stiffness of right wrist, not elsewhere classified"},
    {"code":"M25.642","name":"Stiffness of left hand, not elsewhere classified"},
    {"code":"R49.0","name":"Dysphonia"},
    {"code":"M79.602","name":"Pain in left arm"},
    {"code":"I63.9","name":"Cerebral infarction, unspecified"},
    {"code":"M79.601","name":"Pain in right arm"},
    {"code":"M25.672","name":"Stiffness of left ankle, not elsewhere classified"},
    {"code":"N39.3","name":"Stress incontinence (female) (male)"},
    {"code":"M19.011","name":"Primary osteoarthritis, right shoulder"},
    {"code":"M54.31","name":"Sciatica, right side"},
    {"code":"I97.2","name":"Postmastectomy lymphedema syndrome"},
    {"code":"G35","name":"Multiple sclerosis"},
    {"code":"M75.102","name":"Unspecified rotator cuff tear or rupture of left shoulder, not specified as traumatic"},
    {"code":"G25.0","name":"Essential tremor"},
    {"code":"M79.641","name":"Pain in right hand"},
    {"code":"M46.1","name":"Sacroiliitis, not elsewhere classified"},
    {"code":"M72.2","name":"Plantar fascial fibromatosis"},
    {"code":"M75.121","name":"Complete rotator cuff tear or rupture of right shoulder, not specified as traumatic"},
    {"code":"M76.62","name":"Achilles tendinitis, left leg"},
    {"code":"R51.9","name":"Headache, unspecified"},
    {"code":"M77.11","name":"Lateral epicondylitis, right elbow"},
    {"code":"M25.541","name":"Pain in joints of right hand"},
    {"code":"M25.611","name":"Stiffness of right shoulder, not elsewhere classified"},
    {"code":"R10.2","name":"Pelvic and perineal pain"},
    {"code":"M17.0","name":"Bilateral primary osteoarthritis of knee"},
    {"code":"M25.632","name":"Stiffness of left wrist, not elsewhere classified"},
    {"code":"M75.41","name":"Impingement syndrome of right shoulder"},
    {"code":"N39.46","name":"Mixed incontinence"},
    {"code":"G80.1","name":"Spastic diplegic cerebral palsy"},
    {"code":"F80.1","name":"Expressive language disorder"},
    {"code":"M54.42","name":"Lumbago with sciatica, left side"},
    {"code":"M17.12","name":"Unilateral primary osteoarthritis, left knee"},
    {"code":"M23.51","name":"Chronic instability of knee, right knee"},
    {"code":"M76.61","name":"Achilles tendinitis, right leg"},
    {"code":"M53.2X5","name":"Spinal instabilities, thoracolumbar region"},
    {"code":"R27.0","name":"Ataxia, unspecified"},
    {"code":"R47.1","name":"Dysarthria and anarthria"},
    {"code":"R41.89","name":"Other symptoms and signs involving cognitive functions and awareness"},
    {"code":"M48.062","name":"Spinal stenosis, lumbar region with neurogenic claudication"},
    {"code":"R10.30","name":"Lower abdominal pain, unspecified"},
    {"code":"G20.C","name":"Parkinsonism, unspecified"},
    {"code":"M79.642","name":"Pain in left hand"},
    {"code":"N39.41","name":"Urge incontinence"},
    {"code":"M17.11","name":"Unilateral primary osteoarthritis, righ knee"},
    {"code":"M54.32","name":"Sciatica, left side"},
    {"code":"M25.671","name":"Stiffness of right ankle, not elsewhere classified"},
    {"code":"M25.542","name":"Pain in joints of left hand"},
    {"code":"M76.32","name":"Iliotibial band syndrome, left leg"},
    {"code":"G62.9","name":"Polyneuropathy, unspecified"},
    {"code":"M25.612","name":"Stiffness of Left Shoulder"},
    {"code":"G20.B2","name":"Parkinson's disease with dyskinesia, with fluctuations"},
    {"code":"M19.012","name":"Osteoarthritis of Left shoulder"},
    {"code":"R49.8 ","name":"Other voice and resonance dx"},
    {"code":"R47.01 ","name":"Aphasia"},
    {"code":"R47.1 ","name":"Dysarthria"},
    {"code":"R48.2 ","name":"Apraxia"},
    {"code":"F80.1 ","name":"Expressive language disorder"},
    {"code":"R13.9 ","name":"Dysphagia"},
    {"code":"R41.844 ","name":"Frontal lobe and executive function deficit"}];