const mongoose = require('mongoose')

const objectiveSchema = new mongoose.Schema({
    appointmentId: {
        type: mongoose.Schema.ObjectId,
        ref: "appointments"
      },
    soap_note_type: {
        type: String,
        enum: ['initial_examination','daily_note','progress_note','discharge_note'],
        default: 'initial_examination'
    },
    protocols:[],
    precautions: { type: String, default: ""},
    patient_consent: { type: String, default: ""},
    chaperone: [{
        flag: String,
        name: String
    }],
    observation: { type: String, default: ""},
    range_of_motion: { type: String, default: ""},
    strength: { type: String, default: ""},
    neurological: { type: String, default: ""},
    special_test: { type: String, default: ""},
    palpation: { type: String, default: ""},
    outcome_measures:{
        name:{ type: String, default:""},
        neck_rate_your_pain:{ type: String, default:""},
        pain_intensity:{ type: String, default:""},
        personal_care:{ type: String, default:""},
        lifting:{ type: String, default:""},
        headache:{ type: String, default:""},
        recreation:{ type: String, default:""},
        reading:{ type: String, default:""},
        work:{ type: String, default:""},
        sleeping:{ type: String, default:""},
        concentration:{ type: String, default:""},
        driving:{ type: String, default:""},
        score:{ type: String, default:""},     
        quick_dash_question1:{ type: String, default:""}, 
        quick_dash_question2:{ type: String, default:""}, 
        quick_dash_question3:{ type: String, default:""}, 
        quick_dash_question4:{ type: String, default:""}, 
        quick_dash_question5:{ type: String, default:""}, 
        quick_dash_question6:{ type: String, default:""}, 
        quick_dash_question7:{ type: String, default:""}, 
        quick_dash_question8:{ type: String, default:""}, 
        quick_dash_question9:{ type: String, default:""}, 
        quick_dash_question10:{ type: String, default:""}, 
        quick_dash_question11:{ type: String, default:""}, 
        quick_dash_score:{ type: String, default:""}, 
        oswestry_pain_intensity:{ type: String, default:""}, 
        oswestry_standing:{ type: String, default:""}, 
        oswestry_personal_care:{ type: String, default:""}, 
        oswestry_sleeping:{ type: String, default:""}, 
        oswestry_lifting:{ type: String, default:""}, 
        oswestry_social_life:{ type: String, default:""}, 
        oswestry_walking:{ type: String, default:""}, 
        oswestry_traveling:{ type: String, default:""}, 
        oswestry_sitting:{ type: String, default:""}, 
        oswestry_employment_homemaking:{ type: String, default:""},
        lefs_question1:{ type: String, default:""},
        lefs_question2:{ type: String, default:""},
        lefs_question3:{ type: String, default:""},
        lefs_question4:{ type: String, default:""},
        lefs_question5:{ type: String, default:""},
        lefs_question6:{ type: String, default:""},
        lefs_question7:{ type: String, default:""},
        lefs_question8:{ type: String, default:""},
        lefs_question9:{ type: String, default:""},
        lefs_question10:{ type: String, default:""},
        lefs_question11:{ type: String, default:""},
        lefs_question12:{ type: String, default:""},
        lefs_question13:{ type: String, default:""},
        lefs_question14:{ type: String, default:""},
        lefs_question15:{ type: String, default:""},
        lefs_question16:{ type: String, default:""},
        lefs_question17:{ type: String, default:""},
        lefs_question18:{ type: String, default:""},
        lefs_question19:{ type: String, default:""},
        lefs_question20:{ type: String, default:""},
        lefs_score:{ type: String, default:""},
        fabq_1_rate_your_pain:{ type: String, default:""},
        fabq_2_rate_your_pain:{ type: String, default:""},
        fabq_3_rate_your_pain:{ type: String, default:""},
        fabq_4_rate_your_pain:{ type: String, default:""},
        fabq_5_rate_your_pain:{ type: String, default:""},
        fabq_6_rate_your_pain:{ type: String, default:""},
        fabq_7_rate_your_pain:{ type: String, default:""},
        fabq_8_rate_your_pain:{ type: String, default:""},
        fabq_9_rate_your_pain:{ type: String, default:""},
        fabq_10_rate_your_pain:{ type: String, default:""},
        fabq_11_rate_your_pain:{ type: String, default:""},
        fabq_12_rate_your_pain:{ type: String, default:""},
        fabq_13_rate_your_pain:{ type: String, default:""},
        fabq_14_rate_your_pain:{ type: String, default:""},
        fabq_15_rate_your_pain:{ type: String, default:""},
        fabq_16_rate_your_pain:{ type: String, default:""},
        fabq_score:{ type: String, default:""},
        mctsib_conditio1_1:{ type: String, default:""},
        mctsib_conditio1_2:{ type: String, default:""},
        mctsib_conditio1_3:{ type: String, default:""},
        mctsib_conditio2_1:{ type: String, default:""},
        mctsib_conditio2_2:{ type: String, default:""},
        mctsib_conditio2_3:{ type: String, default:""},
        mctsib_conditio3_1:{ type: String, default:""},
        mctsib_conditio3_2:{ type: String, default:""},
        mctsib_conditio3_3:{ type: String, default:""},
        mctsib_conditio4_1:{ type: String, default:""},
        mctsib_conditio4_2:{ type: String, default:""},
        mctsib_conditio4_3:{ type: String, default:""},
        mctsib_total:{ type: String, default:""},
        sts_number:{ type: String, default:""},
        sts_score:{ type: String, default:""},
    },
    add_exercise:{
        exercises:{ type: String, default:""},
        exercise_date:{ type: Date},
        sets:{ type: String, default:""},
        reps:{ type: String, default:""},
        weight_resistance:{ type: String, default:""},
        distance:{ type: String, default:""},
        exercise_time:{ type: String, default:""},
        exercise_time_mints:{ type: String, default:""},
    },
    slp: { type: String, default: ""},
    ot: { type: String, default: ""},
    treatment_provided: { type: String, default: ""},
    status: { type: String, enum: ['Draft', 'Finalize'], default: 'Draft' },
    createdBy: {
        type: mongoose.Schema.ObjectId,
        ref: "users"
    },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
})

module.exports = mongoose.model('objective', objectiveSchema)